[package]
name = "shiny-robots"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]

[dependencies]
cadence = "0.17"
failure = "0.1.1"
futures = "0.1.18"
hyper = "0.12.13"
hyper-tls = "0.3"
indexmap = { version = "1.0.0", features = ["serde-1"] }
lazy_static = "1.0.0"
lru-cache = "0.1.1"
maud = "0.21"
relative-path = { version = "0.4", features = ["serde"] }
route-recognizer = "0.1.12"
rustsec = "0.12.0"
semver = { version = "0.9.0", features = ["serde"] }
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
shared_failure = "0.1.0"
slog = "2.1.1"
slog-json = "2.2.0"
tokio-threadpool = "0.1.2"
tokio-service = "0.1.0"
toml = "0.5"
try_future = "0.1.1"

[dependencies.badge]
version = "0.2.0"
path = "libs/badge"

[build-dependencies]
sass-rs = "0.2.1"
